name: CI Pipeline - Build dan Push Docker Image

on:
    push:
        branches: [ "main" ] # trigger pipeline ini setiap kali ada push di branch main
    
jobs:
    build_and_push:
        runs-on: ubuntu-latest # menggunakan server virtual Ubuntu
        steps:
        - name: Checkout kode
          uses: actions/checkout@v3
        
        # (Optional) Langkah untuk linting atau unit test
        - name: Login ke Docker Hub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

        - name: Build dan push Docker image
          uses: docker/build-push-action@v4
          with: 
            context: .
            file: ./Dockerfile
            push: true
            tags: spicysss/proyek-devops-dasar:v0.1